# Generated by Django 5.0.6 on 2025-10-19 14:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('confidence_score', models.FloatField(default=1.0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='useractivity',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='application_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='compressed_embedding',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='content_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='file_name',
            field=models.CharField(blank=True, default='default_file', max_length=255),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='importance_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='window_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='application',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='screenshot_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='useractivity',
            name='window_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usermemoryprofile',
            name='memory_quota_mb',
            field=models.FloatField(default=1024),
        ),
        migrations.AddField(
            model_name='usermemoryprofile',
            name='total_memory_used_mb',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='memorytier',
            name='duration_days',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='memorytier',
            name='name',
            field=models.CharField(choices=[('instant', 'Instant Recall (5 dakika)'), ('short_term', 'Short Term (24 saat)'), ('long_term', 'Long Term (30 gun)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usermemoryprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['user', 'memory_tier', 'expires_at'], name='memory_memo_user_id_570550_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['user', 'last_accessed'], name='memory_memo_user_id_f05168_idx'),
        ),
        migrations.AddIndex(
            model_name='memoryitem',
            index=models.Index(fields=['user', 'created_at'], name='memory_memo_user_id_312122_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'timestamp'], name='memory_user_user_id_27e96b_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivity',
            index=models.Index(fields=['user', 'activity_type'], name='memory_user_user_id_ba8962_idx'),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='timelineevent',
            index=models.Index(fields=['user', 'timestamp'], name='memory_time_user_id_a02fc2_idx'),
        ),
    ]
