# Generated by Django 5.0.6 on 2025-10-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_timelineevent_alter_useractivity_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='memoryitem',
            name='memory_memo_user_id_570550_idx',
        ),
        migrations.RemoveIndex(
            model_name='memoryitem',
            name='memory_memo_user_id_f05168_idx',
        ),
        migrations.RemoveIndex(
            model_name='memoryitem',
            name='memory_memo_user_id_312122_idx',
        ),
        migrations.RemoveField(
            model_name='memoryitem',
            name='importance_score',
        ),
        migrations.AlterField(
            model_name='memoryitem',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memoryitem',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
