# Generated by Django 5.0.6 on 2025-10-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_remove_memoryitem_memory_memo_user_id_570550_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memorytier',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='memorytier',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=1440),
        ),
        migrations.AlterField(
            model_name='memorytier',
            name='name',
            field=models.CharField(choices=[('instant', 'Instant Recall'), ('short_term', 'Short Term'), ('long_term', 'Long Term')], max_length=20, unique=True),
        ),
    ]
