# Generated by Django 5.0.6 on 2025-11-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0004_remove_memorytier_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryitem',
            name='graph_metadata',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='graph_topology',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='is_semantically_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='semantic_features',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memoryitem',
            name='superpixel_map',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
