# Generated by Django 5.0.6 on 2025-12-08 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0005_memoryitem_graph_metadata_memoryitem_graph_topology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.FloatField(help_text='Videonun kaçıncı saniyesi')),
                ('vector_embedding', models.BinaryField(help_text='Bu karenin CLIP vektörü')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_frames', to='memory.memoryitem')),
            ],
        ),
    ]
