# Generated by Django 5.0.6 on 2025-12-09 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0006_videoframe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bilinmeyen Kişi', max_length=100)),
                ('is_identified', models.BooleanField(default=False)),
                ('cover_photo', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encoding', models.BinaryField()),
                ('location_top', models.IntegerField()),
                ('location_right', models.IntegerField()),
                ('location_bottom', models.IntegerField()),
                ('location_left', models.IntegerField()),
                ('memory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_faces', to='memory.memoryitem')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faces', to='memory.person')),
            ],
        ),
    ]
