# Generated by Django 5.0.6 on 2025-10-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_groupfile_uploaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
    ]
