# Generated by Django 5.0.6 on 2025-10-14 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_fileshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileshare',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
