# Generated by Django 5.0.6 on 2025-10-15 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_fileshare_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='view_duration',
            field=models.CharField(choices=[('10s', '10 saniye'), ('30s', '30 saniye'), ('1m', '1 dakika'), ('5m', '5 dakika'), ('1h', '1 saat'), ('video', 'Video süresi'), ('unlimited', 'Süresiz')], default='unlimited', max_length=20),
        ),
    ]
