# Generated by Django 5.0.6 on 2025-10-15 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_file_view_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileshare',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='files.file'),
        ),
    ]
