# Generated by Django 5.0.6 on 2025-10-17 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_fileshare_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
    ]
