# Generated by Django 5.0.6 on 2025-10-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_delete_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='can_download',
            field=models.BooleanField(default=True),
        ),
    ]
