# Generated by Django 5.0.6 on 2025-10-17 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0010_file_can_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='is_revoked',
            field=models.BooleanField(default=False),
        ),
    ]
